#!/usr/bin/env fish

set -l YAZI_FLAVOR (theme_pick catppuccin-mocha catppuccin-latte); or exit 1

# Both keys point at the same flavor so Yazi follows C_THEME rather than its
# own terminal-background detection. New Yazi instances pick this up.
printf '# Generated by yazi/theme.fish — do not edit by hand.\n[flavor]\ndark  = "%s"\nlight = "%s"\n' \
    $YAZI_FLAVOR $YAZI_FLAVOR >"$DOTFILES/yazi/config/theme.toml"
