#!/usr/bin/env fish

switch $C_THEME
    case dark
        set YAZI_FLAVOR catppuccin-mocha
    case light
        set YAZI_FLAVOR catppuccin-latte
    case "*"
        exit 1
end

# Both keys point at the same flavor so Yazi follows C_THEME rather than its
# own terminal-background detection. New Yazi instances pick this up.
printf '# Generated by yazi/theme.fish — do not edit by hand.\n[flavor]\ndark  = "%s"\nlight = "%s"\n' \
    $YAZI_FLAVOR $YAZI_FLAVOR >"$DOTFILES/yazi/config/theme.toml"
